name: "Cronjob"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *'
  push:
    branches:
      - 'main'

jobs:
  update-readme:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'
      - name: Prepare
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          mkdir .tmp
      - name: Collect market
        run: |
          go clean -cache
          go clean -modcache
          go install github.com/adzmatheus/stonks-market@latest
          stonks-market update-stonks --days=5 --ticker=^BVSP  --stonks-api-key="${{ secrets.BRAPI_API_KEY }}" --template-file='templates/stonks.md.tpl' --out-file='.tmp/stonks.md.tpl'
      - name: Merge templates
        run: |
          go install github.com/huantt/merge-templates@v1.0.0
          merge-templates README.md 'templates/README.md.tpl' '.tmp/stonks.md.tpl'
      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          
          if git diff --cached --exit-code; then
            echo "No changes to commit."
            exit 0
          else
            git commit -m "update"
            git rebase main
            git push origin main
          fi
